file_management/urls.py
from django.urls import path

from file_management.views import FileUpload, ListFiles, DeleteFile

urlpatterns = [
    path('upload-file/', FileUpload.as_view(), name='upload-file'),
    path('list-file/', ListFiles.as_view(), name='list-file'),
    path('delete-file/<uuid:pk>/', DeleteFile.as_view(), name="delete-file"),
]

task_management/urls.py
from django.urls import path

from task_management.views import ListUserTask, CreateTask, UpdateTask, DeleteTask

urlpatterns = [
    path("list/", ListUserTask.as_view(), name="list-task"),
    path("create/", CreateTask.as_view(), name="create-task"),
    path("update/<int:pk>/", UpdateTask.as_view(), name="update-task"),
    path("delete/<int:pk>/", DeleteTask.as_view(), name="delete-task"),
]

todo_list/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("user_management.urls")),
    path("tasks/", include("task_management.urls")),
    path("files/", include("file_management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.urls import path

from user_management.views import LoginUser, SignupUser, LogOutView

urlpatterns = [
    path("login/", LoginUser.as_view(), name="login-user"),
    path("logout/", LogOutView.as_view(), name="logout-user"),
    path("signup/", SignupUser.as_view(), name="signup-user"),
]

file_management/models.py
import uuid
from django.db import models

from user_management.models import User


class File(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_time = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='task/')
    uploader = models.ForeignKey(User, related_name='files', on_delete=models.CASCADE)

task_management/models.py
from django.db import models

from file_management.models import File
from user_management.models import User


class Task(models.Model):
    CREATED = 1
    DOING = 2
    DONE = 3
    CANCEL = 4
    PAUSE = 5
    ATTRIBUTE_TYPES = (
        (CREATED, "task_create"),
        (DOING, "task_doing"),
        (DONE, "task_done"),
        (CANCEL, "task_cancel"),
        (PAUSE, "task_stop"),
    )

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    status = models.PositiveSmallIntegerField(default=CREATED, choices=ATTRIBUTE_TYPES)

    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="tasks"
    )
    members = models.ManyToManyField(User, blank=True)
    files = models.ManyToManyField(File, blank=True)

    def __str__(self):
        return f"{self.title} - {self.status}"

user_management/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    phone_number = models.CharField(max_length=11)

    def __str__(self):
        return self.first_name

file_management/forms.py
from django import forms
from file_management.models import File


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ('file',)

    def __init__(self, *args, **kwargs):
        super(FileForm, self).__init__(*args, **kwargs)
        self.fields['file'].required = False

task_management/forms.py
from task_management.models import Task
from django import forms


class TaskCreateForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('title', 'description', 'members', 'files')


class UpdateTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('title', 'description', 'members', 'status')


class DeleteTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('title', 'description', 'members', 'status')

user_management/forms.py
from django import forms
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from user_management.models import User


class UserSignUp(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "password",
            "confirm_password",
            "phone_number",
        )

    def clean_phone_number(self):
        phone_number = self.cleaned_data["phone_number"]
        if len(phone_number) != 11:
            raise ValidationError("length is to 11")
        return phone_number

    def clean_confirm_password(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data["confirm_password"]
        if password != confirm_password:
            raise ValidationError("Passwords does not match")
        cleaned_data['password'] = make_password(cleaned_data['password'])
        return cleaned_data

file_management/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView

from file_management.forms import FileForm
from file_management.models import File


class FileUpload(LoginRequiredMixin, CreateView):
    model = File
    form_class = FileForm
    template_name = 'file_management/upload_file.html'
    success_url = reverse_lazy('create-task')

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.uploader = self.request.user
        instance.save()
        return super().form_valid(form)


class ListFiles(LoginRequiredMixin, ListView):
    model = File
    template_name = "file_management/list_file.html"

    def get_queryset(self):
        return super().get_queryset().filter(
            uploader=self.request.user
        )


class DeleteFile(LoginRequiredMixin, DeleteView):
    model = File
    template_name = 'file_management/delete_file.html'
    success_url = reverse_lazy('list-file')

    def get_queryset(self):
        return super().get_queryset().filter(
            uploader=self.request.user
        )

task_management/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from file_management.models import File
from .forms import TaskCreateForm, UpdateTaskForm
from .models import Task


class ListUserTask(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task_management/list_tasks.html"

    def get_queryset(self):
        return super().get_queryset().filter(
            creator=self.request.user
        )


class CreateTask(LoginRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = "task_management/create_task.html"
    success_url = reverse_lazy("list-task")

    def get_form(self, *args, **kwargs):
        form = super().get_form(None)
        form.fields["files"].queryset = File.objects.filter(uploader=self.request.user)
        return form

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.creator = self.request.user
        instance.save()
        return super().form_valid(form)

    def get_queryset(self):
        super().get_queryset.filter(
            creator=self.request.user
            )


class UpdateTask(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = UpdateTaskForm
    template_name = 'task_management/update_task.html'
    success_url = reverse_lazy('list-task')

    def get_queryset(self):
        return super().get_queryset().filter(
            creator=self.request.user
        )


class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'task_management/delete_task.html'
    success_url = reverse_lazy('list-task')

    def get_queryset(self):
        return super().get_queryset().filter(
            creator=self.request.user
        )

user_management/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from user_management.forms import UserSignUp


class LogOutView(LogoutView):
    next_page = '/auth/login/'


class LoginUser(LoginView):
    template_name = "user_management/user_login.html"
    next_page = reverse_lazy("create-task")


class SignupUser(CreateView):
    form_class = UserSignUp
    template_name = "user_management/sign_up.html"
    success_url = reverse_lazy("login-user")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/file_management/delete_file.html
{% extends 'base.html' %}

{% block title%} delete file {% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ object }}"?</p>
	<input type="submit" value="Confirm">
</form>

{% endblock %}

templates/file_management/list_file.html
{% extends 'base.html'%}

{% block title %}list files{% endblock %}

{% block content %}
  <h2>list of files</h2>

    {% for task in object_list %}

    <h3>
        id:{{task.id}}
        creator:{{task.uploader}}
    </h3>
    <a href="{% url 'delete-file' task.id %}"><button type="submit">delete file</button> </a>


    {% endfor %}
{% endblock %}

templates/file_management/upload_file.html
{% extends 'base.html' %}

{% block title %} upload-files {% endblock %}

{% block content %}
uploader name:{{request.user}}
<form enctype="multipart/form-data" method="post" action="">{{form.as_p}}{% csrf_token %}
    <button type="submit">upload file</button>
</form>
<a href="{% url 'logout-user' %}"><button type="submit"> log out</button></a>
<a href="{% url 'list-task' %}"><button type="submit"> show list task</button></a>
<a href="{% url 'list-file' %}"><button type="submit"> show list file</button></a>

{% endblock %}

templates/task_management/create_task.html
{% extends 'base.html'%}

{% block title%} create-task {% endblock %}
{% block content %}
<h2>welcome {{request.user}}</h2>
<form method="post" action="">{{form.as_p}} {% csrf_token %}
      <button type="submit">create task</button>
</form>
<a href="{% url 'logout-user' %}"><button type="submit"> log out</button></a>
<a href="{% url 'list-task' %}"><button type="submit"> show list</button></a>
<a href="{% url 'upload-file' %}"><button type="submit"> upload file</button></a>


{% endblock %}

templates/task_management/delete_task.html
{% extends 'base.html' %}

{% block title%} delete task {% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ object }}"?</p>
	<input type="submit" value="Confirm">
</form>

{% endblock %}

templates/task_management/list_tasks.html
{% extends 'base.html'%}
{% block title %}Hi {{request.user}}{% endblock %}
{% block content %}
  <h2>list of task doing</h2>
<ul>
    {% for task in object_list %}

    <h3>
        <li>
            id:{{task.id}}
            title:{{task.title}} -
    description:{{task.description}} -
    status:{{task.get_status_display}} -
        creator:{{task.creator}}
        - members:{% for member in task.members.all %}{{ member.username }},{% endfor %}
    </li>
    </h3>
    <a href="{% url 'update-task' task.id %}"><button type="submit">Edit</button> </a>
    <a href="{% url 'delete-task' task.id %}"><button type="submit">delete</button> </a>
    <a href="{% url 'upload-file'  %}"><button type="submit">upload file</button> </a>


    {% endfor %}

</ul>
 <a href="{% url 'create-task' %}"><button type="submit">create task</button> </a>
<a href="{% url 'logout-user' %}"><button type="submit"> log out</button></a>
{% endblock %}

templates/task_management/update_task.html
{% extends 'base.html' %}

{% block title%} update and edit task {% endblock %}

{% block content %}
<form method="post" action="">{{form.as_p}}{% csrf_token %}
<button type="submit">save update</button>
</form>

<a href="{% url 'logout-user' %}"><button type="submit"> log out</button></a>
{% endblock %}

templates/user_management/sign_up.html
{% extends 'base.html'%}
{% block title %} signup page{% endblock %}
{% block content %}


<form method="post" action="">{% csrf_token %}
{{ form.as_p }} <button type="submit">create account</button>
</form>
{% endblock %}

templates/user_management/user_login.html
{% extends 'base.html'%}
{% block title %}login user{% endblock %}
{% block content %}

<form method="post" action="">{% csrf_token %}
{{ form.as_p }} <button type="submit">Log in</button>
</form>
<a href="{% url 'signup-user' %}"><button type="submit">sign up</button> </a>
{% endblock %}